// WARNING: Do not edit, this file is autogenerated.

package pkg

// IgniteKatanas is used to execute a function.
func IgniteKatana(function string) error {

  return nil
}

// ListKatanas is used to list all functions.
func ListKatanas() error {

  return nil
}
