package main

import (
	"fmt"
	"strings"
	"runtime"

	"github.com/fatih/color"
	"github.com/minio/cli"
	"github.com/influx6/shogun/.shogun/cmd/chop/pkg"
)


// vars ...
var (
 binHash = ""
 binName = "chop"
 Version = "1.0"
 helpTemplate = `NAME:
{{.Name}} - {{.Usage}}

VERSION:
{{.Version}}

DESCRIPTION:
{{.Description}}

USAGE:
{{.Name}} {{if .Flags}}[flags] {{end}}command{{if .Flags}}{{end}} [arguments...]

FLAGS:
	{{range .Flags}}{{.}}
	{{end}}{{end}}

COMMANDS:
	{{range .Commands}}{{join .Names ", "}}{{ "\t" }}{{.Usage}}
	{{end}}{{if .Flags}}
`
)

func main(){
	app := cli.NewApp()
	app.Name = "chop"
	app.Author = ""
	app.Usage = "chop [command]"
  app.Version = Version
	app.Flags = []cli.Flag{}
	app.Description = "chop generated by shogun"
	app.CustomAppHelpTemplate = helpTemplate
  app.Action = mainAction

	app.Commands = []cli.Command{
		{
			Name:   "version",
			Action: versionAction,
			Flags:  []cli.Flag{},
		},
		{
			Name:   "hash",
			Action: hashAction,
			Flags:  []cli.Flag{},
		},
		{
			Name:   "list",
			Action: listAction,
			Flags:  []cli.Flag{},
		},
		{
			Name:   "help",
			Action: helpAction,
			Flags:  []cli.Flag{
				cli.BoolFlag{
					Name:  "f,full",
					Usage: "-f=true",
				},
				cli.BoolFlag{
					Name:  "s,source",
					Usage: "-s=true",
				},
      },
		},
  }
}

func versionAction(c *cli.Context) {
	fmt.Println(color.BlueString(fmt.Sprintf("%s version %s %s/%s; of the Shogun.", binName, Version, runtime.GOOS, runtime.GOARCH)))
}

func mainAction(c *cli.Context) {
}

func hashAction(c *cli.Context) {
	fmt.Println(binHash)
}

func listAction(c *cli.Context) {
  fmt.Println("Samurai below are your katana functions")
	pkg.ListKatanas()
}

func helpAction(c *cli.Context) {
  fmt.Printf("Samurai must always seek help in the Shogunate\n\n")

  funcName := c.Args().First()
  withSource := c.Bool("source")
  fullComment := c.Bool("full")

}
